update pre-commit script and documentation
## What
Update the `pre-commit` script to abort on errors and stage generated documentation.

## Why
Because documents weren't commited with the initial batch of staged files and you had to amend or commit them separately

## How
- Added `set -e` to abort the commit if any command fails.
- Included a command to stage all changes in the `docs` directory.

## Testing
n/a

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -9,8 +9,13 @@ if [ -s "$NVM_DIR/nvm.sh" ]; then
   . "$NVM_DIR/nvm.sh"
 fi
 
+# Abort the commit iif anything returns non 0 exit code
+set -e
+
 # Run your checks
 npm run validate-manifest
 npm run document
+# Stage the generated docs
+git add -A docs
 npm run validate-guides-translations
 npx eslint . --max-warnings 1000
